name: 'Notion Sync Action'
description: 'Sincroniza y enlaza commits de GitHub en una base de datos de Notion'
branding:
  icon: 'arrow-up-right'
  color: 'black'

inputs:
  notion_token:
    description: 'Token de la API de Notion'
    required: true
  notion_commits_db_id:
    description: 'ID de la base de datos de Commits'
    required: true
  notion_tareas_db_id:
    description: 'ID de la base de datos de Tareas'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Set up Node.js 24
      uses: actions/setup-node@v4
      with:
        node-version: '24'

    - name: Install dependencies
      run: npm install --prefix ${{ github.action_path }}
      shell: bash

    # Forzamos el mapeo de inputs hacia las variables que el script lee con process.env
    - name: Run script
      run: node ${{ github.action_path }}/sync-notion.js
      shell: bash
      env:
        NOTION_TOKEN: ${{ inputs.notion_token }}
        NOTION_COMMITS_DB_ID: ${{ inputs.notion_commits_db_id }}
        NOTION_TAREAS_DB_ID: ${{ inputs.notion_tareas_db_id }}
        COMMIT_MESSAGE: ${{ github.event.head_commit.message }}
        COMMIT_URL: ${{ github.event.head_commit.url }}
