name: 'Notion Sync Action'
description: 'Sincroniza y enlaza commits de GitHub en una base de datos de Notion'
branding:
  icon: 'arrow-up-right'
  color: 'black'

runs:
  using: 'composite'
  steps:
    # 1. Forzamos al servidor de GitHub a instalar y usar Node.js 24
    - name: Set up Node.js 24
      uses: actions/setup-node@v4
      with:
        node-version: '24'

    # 2. Instalamos las dependencias necesarias
    - name: Install dependencies
      run: npm install --prefix ${{ github.action_path }}
      shell: bash

    # 3. Ejecutamos el script apuntando a su ruta correcta
    - name: Run script
      run: node ${{ github.action_path }}/sync-notion.js
      shell: bash
